#!/bin/bash

set -eo pipefail
[[ -n "${DEBUG:-}" ]] && set -x

export DOTFILES_DIR="$HOME/.dotfiles"

# Write symlinks to home directory

echo "Symlinking dotfiles to HOME and/or HOME/.config directories. This may overwrite your existing '.zshrc' and other dotfiles. Do you wish to proceed? (y/n)"
read response

if [[ "$response" == "y" || "$response" == "Y" ]]; then
	echo "Symlinking dotfiles to home directory."

	ln -sfv "$DOTFILES_DIR/.editorconfig" ~
	ln -sfv "$DOTFILES_DIR/.gitconfig" ~
	ln -sfv "$DOTFILES_DIR/.gitignore" ~
	ln -sfv "$DOTFILES_DIR/.zshrc" ~
  	ln -sfv "$DOTFILES_DIR/.tool-versions" ~
  	ln -sfv "$DOTFILES_DIR/starship.toml" ~/.config/starship.toml
else
	echo "No symlinks written"
	exit 0
fi;

echo "Do you wish to brew install packages? (y/n)"
read response

if [[ "$response" == "y" || "$response" == "Y" ]]; then
  echo "Installing brew packages"

  DEBUG=$DEBUG "$DOTFILES_DIR/scripts/brew_install"
fi;
