format = """\
	$username\
	$directory\
	$git_branch\
	$line_break\
	$aws\
	$kubernetes\
	$character\
	$line_break\
"""

[username]
show_always = true
style_user = "fg:190"
style_root = "bold red"

[directory]
truncate_to_repo = true
truncation_length = 8
style = "fg:110"

[git_branch]
symbol = ""
style = "fg:190"

[aws]
symbol = "aws:"
style = "fg:110"
format = '[$symbol$profile(\($region\))]($style) '

[kubernetes]
symbol = "k8s:"
disabled = false
style = "fg:190"
format = '[$symbol$context( \($namespace\))]($style) '

