#!/bin/bash
# Based on https://openfolder.sh/macos-migrations-with-brewfile
DEBUG=${DEBUG:-false}

set -eo pipefail
[[ "${DEBUG}" == "true" ]] && set -x

# Check for Homebrew installed
if command -v brew > /dev/null 2>&1 ; then
	echo "Homebrew already installed. Fetching newest version of Homebrew..."
	brew update
else	
	# Check for xcode-select CLI installed
	if ls -l /Library/Developer/CommandLineTools > /dev/null 2>&1 ; then
		echo "xcode-select command line tools installed. installing Homebrew..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
	else
		echo "Installing xcode-select command line tools..."
		xcode-select --install
	fi
fi

# Check for Mac App Store CLI
if brew info mas > /dev/null 2>&1 ; then
	echo "Mac App Store CLI already installed"
else
	echo "Installing Max App Store CLI..."
	brew install mas
fi

# brew install formulae
brew bundle --file=$HOME/.dotfiles/Brewfile
