#!/bin/bash
# Based on https://openfolder.sh/macos-migrations-with-brewfile

set -e -o pipefail
[[ -n "${DEBUG:-}" ]] && set -x

# Check for Homebrew installed
which -s brew
if [[ $? != 0 ]] ; then
	ls -l /Library/Developer/CommandLineTools
	
	# Check for xcode-select CLI installed
	if [[ $? != 0 ]] ; then
		echo "Installing xcode-select command line tools..."
		xcode-select --install
	else
		echo "xcode-select command line tools installed. Installing Homebrew..."
		ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi
else
	echo "Homebrew already installed. Fetching newest version of Homebrew..."
	brew update
fi

# Check for homebrew/cask
brew tap | grep "^homebrew/cask$"
if [[ $? != 0 ]] ; then
	echo "Installing Homebrew Cask..."
	brew tap homebrew/cask
else
	echo "Homebrew Cask already installed"
fi

# Check for Mac App Store CLI
brew info mas > /dev/null
if [[ $? != 0 ]] ; then
	echo "Installing Max App Store CLI..."
	brew install mas
else
	echo "Max App Store CLI already installed"
fi

# brew install formulae
brew bundle --file=$HOME/.dotfiles/Brewfile
